export const MEMORY_ADMIN_PATHS = Object.freeze({
  objects: 'objects',
  objectCreate: 'objects/create',
  objectDetail: 'objects/detail',
  objectUpdate: 'objects/update',
  objectRevisions: 'objects/revisions',
  objectSources: 'objects/sources',
  objectMergePreview: 'objects/merge/preview',
  objectMerge: 'objects/merge',
  objectSupersede: 'objects/supersede',
  objectArchive: 'objects/archive',
  objectBatch: 'objects/batch',
  conflicts: 'conflicts',
  conflictResolve: 'conflicts/resolve',
  identities: 'identities',
  ownerCreate: 'identities/owners/create',
  ownerUpdate: 'identities/owners/update',
  aliasLink: 'identities/aliases/link',
  aliasMove: 'identities/aliases/move',
  ownerMergePreview: 'identities/owners/merge/preview',
  ownerMerge: 'identities/owners/merge',
  maintenanceStatus: 'maintenance/status',
  indexRetry: 'maintenance/index/retry',
});
