import { createContext, useContext } from 'react';

export type Locale = 'zh' | 'en' | 'ru';
type Messages = Record<string, string>;

const dictionaries: Record<Locale, Messages> = {
  zh: {
    servers: '服务器', trends: '在线趋势', settings: '运行配置', memoryConfig: '记忆配置', sourceUpdates: '来源更新', sourceForceRefresh: '强制检查更新', sourceRefreshing: '检查中…', sourceStatusCurrent: '已是最新', sourceStatusNewVersion: '发现新版本', sourceStatusNewCommits: '发现新提交', sourceStatusChanged: '来源已变更', sourceStatusUnavailable: '暂不可用', overview: '记忆概览', memories: '记忆管理', recall: '召回测试', graph: '知识图谱', theme: '主题', light: '浅色', dark: '深色',
    loading: '正在加载', empty: '暂无数据', retry: '重试', memoryUnavailable: 'Memory 服务当前不可用', search: '搜索', refresh: '刷新', save: '保存', saving: '保存中…', cancel: '取消', delete: '删除', deleting: '删除中…', archive: '归档', previous: '上一页', next: '下一页', details: '详情', backups: '版本备份', sessions: '活跃会话', importance: '重要性', status: '状态', type: '类型', created: '创建时间', updated: '更新时间', content: '内容', query: '查询内容', run: '执行', results: '结果', focus: '定位记忆', recent: '最近概览', batch: '批量操作', selectAll: '全选当前页', total: '总记忆', active: '活跃', archived: '已归档', deleted: '已删除', graphNodes: '图谱节点', atoms: '原子记忆', edit: '编辑', close: '关闭', reason: '更新原因（可选）', noMemoryRoutes: '当前模式不展示 Memory 功能', operationFailed: '操作失败', operationDone: '操作完成', filters: '筛选条件', page: '页', files: '个文件', score: '得分', elapsed: '耗时', keyboardHint: 'Ctrl/⌘ + Enter 执行', graphEmpty: '当前范围暂无图谱数据', enabled: '已启用', disabled: '未启用', initialized: '已初始化', notInitialized: '未初始化',
    records: '条记录', keyword: '关键词', session: '会话 ID', groupChat: '群聊', persona: '人格 ID', all: '全部', sort: '排序', pageSize: '每页数量', selected: '项已选择', select: '选择', pagination: '分页', processing: '处理中…', memoryIndex: '记忆索引', memoryDetail: '记忆详情', deleteMemoryTitle: '删除这条记忆？', deleteMemoryDescription: '此操作将永久删除记忆', deleteSelectedTitle: '删除所选记忆？', deleteSelectedDescription: '将永久删除所选数量：', confirmDelete: '确认删除',
    lastAccess: '最后访问', keyFacts: '关键事实', topics: '主题', updateHistory: '更新历史', graphContext: '图谱上下文', nodes: '节点', edges: '关系', entries: '入口', entry: '入口', scoreBreakdown: '得分明细', openFullDetail: '打开完整详情', invalidMemoryId: '该结果没有可用的整数记忆 ID', hybridRetrieval: '混合召回', noRecallResults: '没有匹配的记忆', recallReady: '等待查询', recallPrompt: '输入查询内容后执行召回测试',
    importanceDistribution: '重要性分布', atomBreakdown: '原子类型分布', noImportanceDistribution: '暂无重要性分布数据', noAtomBreakdown: '暂无原子类型数据', memoryCapability: 'Memory 能力',
    memoryId: '记忆 ID', graphSnapshot: '图谱快照', graphControls: '图谱视图控制', zoomOut: '缩小', zoomIn: '放大', panLeft: '向左平移', panRight: '向右平移', panUp: '向上平移', panDown: '向下平移', resetView: '重置视图', reflowGraph: '重新布局', graphKeyboardHint: '滚轮缩放，拖动空白处平移；拖动节点后会固定位置，重新布局会清除固定；方向键、加减号和数字 0 仍可使用', legend: '图例与关系筛选', matched: '查询匹配', selectedLabel: '当前选择', memoriesLabel: '记忆', unknown: '未知', nodeDetails: '节点详情', memoryDetails: '记忆详情', graphSummary: '图谱摘要', weight: '权重', degree: '连接数', relatedMemories: '关联记忆', retrievalItems: '检索结果', topNodes: '高权重节点', topMemories: '高关联记忆',
    memoryObjects: '记忆对象', memoryConflicts: '冲突', identityMappings: '身份映射', createMemoryObject: '新建对象', revisionHistory: 'Revision 历史', sourceMessages: '来源消息', relationsAndConflicts: '关系与冲突', indexStatus: '索引状态', unresolvedOwners: '未解析 owner', sourceCoverage: '来源覆盖', migrationStatus: '对象迁移', retryIndex: '索引重试', revisionConflictDraftKept: '对象版本冲突，草稿已保留', loadLatestVersion: '加载最新版本',
  },
  en: {
    servers: 'Servers', trends: 'Trends', settings: 'Runtime Settings', memoryConfig: 'Memory Config', sourceUpdates: 'Source Updates', sourceForceRefresh: 'Force Update Check', sourceRefreshing: 'Checking…', sourceStatusCurrent: 'Current', sourceStatusNewVersion: 'New Version', sourceStatusNewCommits: 'New Commits', sourceStatusChanged: 'Source Changed', sourceStatusUnavailable: 'Unavailable', overview: 'Memory Overview', memories: 'Memories', recall: 'Recall Test', graph: 'Knowledge Graph', theme: 'Theme', light: 'Light', dark: 'Dark',
    loading: 'Loading', empty: 'No data', retry: 'Retry', memoryUnavailable: 'Memory service is unavailable', search: 'Search', refresh: 'Refresh', save: 'Save', saving: 'Saving…', cancel: 'Cancel', delete: 'Delete', deleting: 'Deleting…', archive: 'Archive', previous: 'Previous', next: 'Next', details: 'Details', backups: 'Backups', sessions: 'Active Sessions', importance: 'Importance', status: 'Status', type: 'Type', created: 'Created', updated: 'Updated', content: 'Content', query: 'Query', run: 'Run', results: 'Results', focus: 'Focus Memory', recent: 'Recent Overview', batch: 'Batch Actions', selectAll: 'Select Current Page', total: 'Total Memories', active: 'Active', archived: 'Archived', deleted: 'Deleted', graphNodes: 'Graph Nodes', atoms: 'Memory Atoms', edit: 'Edit', close: 'Close', reason: 'Update reason (optional)', noMemoryRoutes: 'Memory features are hidden in this mode', operationFailed: 'Operation failed', operationDone: 'Operation complete', filters: 'Filters', page: 'Page', files: 'files', score: 'Score', elapsed: 'Elapsed', keyboardHint: 'Ctrl/⌘ + Enter to run', graphEmpty: 'No graph data in this range', enabled: 'Enabled', disabled: 'Disabled', initialized: 'Initialized', notInitialized: 'Not initialized',
    records: 'records', keyword: 'Keyword', session: 'Session ID', groupChat: 'Group chat', persona: 'Persona ID', all: 'All', sort: 'Sort', pageSize: 'Page size', selected: 'selected', select: 'Select', pagination: 'Pagination', processing: 'Processing…', memoryIndex: 'Memory index', memoryDetail: 'Memory detail', deleteMemoryTitle: 'Delete this memory?', deleteMemoryDescription: 'This permanently deletes memory', deleteSelectedTitle: 'Delete selected memories?', deleteSelectedDescription: 'This permanently deletes the selected count:', confirmDelete: 'Confirm delete',
    lastAccess: 'Last access', keyFacts: 'Key facts', topics: 'Topics', updateHistory: 'Update history', graphContext: 'Graph context', nodes: 'nodes', edges: 'relations', entries: 'entries', entry: 'Entry', scoreBreakdown: 'Score breakdown', openFullDetail: 'Open full details', invalidMemoryId: 'This result has no valid integer memory ID', hybridRetrieval: 'Hybrid retrieval', noRecallResults: 'No matching memories', recallReady: 'Ready to query', recallPrompt: 'Enter a query and run recall',
    importanceDistribution: 'Importance distribution', atomBreakdown: 'Atom type distribution', noImportanceDistribution: 'No importance distribution data', noAtomBreakdown: 'No atom type data', memoryCapability: 'Memory capability',
    memoryId: 'Memory ID', graphSnapshot: 'Graph snapshot', graphControls: 'Graph view controls', zoomOut: 'Zoom out', zoomIn: 'Zoom in', panLeft: 'Pan left', panRight: 'Pan right', panUp: 'Pan up', panDown: 'Pan down', resetView: 'Reset view', reflowGraph: 'Reflow layout', graphKeyboardHint: 'Use the wheel to zoom and drag empty space to pan; dragged nodes stay fixed until Reflow clears those locks; arrow keys, plus/minus, and 0 still work', legend: 'Legend and relation filters', matched: 'Query match', selectedLabel: 'Selected', memoriesLabel: 'memories', unknown: 'Unknown', nodeDetails: 'Node details', memoryDetails: 'Memory details', graphSummary: 'Graph summary', weight: 'Weight', degree: 'Degree', relatedMemories: 'Related memories', retrievalItems: 'Retrieval items', topNodes: 'Top nodes', topMemories: 'Top memories',
    memoryObjects: 'Memory Objects', memoryConflicts: 'Conflicts', identityMappings: 'Identity Mappings', createMemoryObject: 'Create Object', revisionHistory: 'Revision History', sourceMessages: 'Source Messages', relationsAndConflicts: 'Relations and Conflicts', indexStatus: 'Index Status', unresolvedOwners: 'Unresolved Owners', sourceCoverage: 'Source Coverage', migrationStatus: 'Object Migration', retryIndex: 'Retry Indexing', revisionConflictDraftKept: 'Object version conflict; draft preserved', loadLatestVersion: 'Load Latest Version',
  },
  ru: {
    servers: 'Серверы', trends: 'Тренды', settings: 'Настройки', memoryConfig: 'Настройки памяти', sourceUpdates: 'Обновления источников', sourceForceRefresh: 'Проверить обновления', sourceRefreshing: 'Проверка…', sourceStatusCurrent: 'Актуально', sourceStatusNewVersion: 'Новая версия', sourceStatusNewCommits: 'Новые коммиты', sourceStatusChanged: 'Источник изменён', sourceStatusUnavailable: 'Недоступно', overview: 'Обзор памяти', memories: 'Память', recall: 'Тест поиска', graph: 'Граф знаний', theme: 'Тема', light: 'Светлая', dark: 'Тёмная',
    loading: 'Загрузка', empty: 'Нет данных', retry: 'Повторить', memoryUnavailable: 'Сервис памяти недоступен', search: 'Поиск', refresh: 'Обновить', save: 'Сохранить', saving: 'Сохранение…', cancel: 'Отмена', delete: 'Удалить', deleting: 'Удаление…', archive: 'Архивировать', previous: 'Назад', next: 'Далее', details: 'Детали', backups: 'Резервные копии', sessions: 'Активные сессии', importance: 'Важность', status: 'Статус', type: 'Тип', created: 'Создано', updated: 'Обновлено', content: 'Содержимое', query: 'Запрос', run: 'Выполнить', results: 'Результаты', focus: 'Фокус памяти', recent: 'Обзор', batch: 'Пакетные действия', selectAll: 'Выбрать страницу', total: 'Всего памяти', active: 'Активно', archived: 'Архив', deleted: 'Удалено', graphNodes: 'Узлы графа', atoms: 'Атомы памяти', edit: 'Изменить', close: 'Закрыть', reason: 'Причина обновления (необязательно)', noMemoryRoutes: 'Функции памяти скрыты в этом режиме', operationFailed: 'Ошибка операции', operationDone: 'Операция завершена', filters: 'Фильтры', page: 'Страница', files: 'файлов', score: 'Оценка', elapsed: 'Время', keyboardHint: 'Ctrl/⌘ + Enter для запуска', graphEmpty: 'Нет данных графа', enabled: 'Включено', disabled: 'Отключено', initialized: 'Инициализировано', notInitialized: 'Не инициализировано',
    records: 'записей', keyword: 'Ключевое слово', session: 'ID сессии', groupChat: 'Групповой чат', persona: 'ID персоны', all: 'Все', sort: 'Сортировка', pageSize: 'Размер страницы', selected: 'выбрано', select: 'Выбрать', pagination: 'Страницы', processing: 'Обработка…', memoryIndex: 'Индекс памяти', memoryDetail: 'Детали памяти', deleteMemoryTitle: 'Удалить эту память?', deleteMemoryDescription: 'Память будет удалена навсегда', deleteSelectedTitle: 'Удалить выбранную память?', deleteSelectedDescription: 'Будет удалено записей:', confirmDelete: 'Подтвердить удаление',
    lastAccess: 'Последний доступ', keyFacts: 'Ключевые факты', topics: 'Темы', updateHistory: 'История обновлений', graphContext: 'Контекст графа', nodes: 'узлы', edges: 'связи', entries: 'записи', entry: 'Запись', scoreBreakdown: 'Состав оценки', openFullDetail: 'Открыть полные детали', invalidMemoryId: 'У результата нет целого ID памяти', hybridRetrieval: 'Гибридный поиск', noRecallResults: 'Совпадений нет', recallReady: 'Ожидание запроса', recallPrompt: 'Введите запрос и запустите поиск',
    importanceDistribution: 'Распределение важности', atomBreakdown: 'Типы атомов', noImportanceDistribution: 'Нет распределения важности', noAtomBreakdown: 'Нет данных по типам атомов', memoryCapability: 'Возможности памяти',
    memoryId: 'ID памяти', graphSnapshot: 'Снимок графа', graphControls: 'Управление графом', zoomOut: 'Уменьшить', zoomIn: 'Увеличить', panLeft: 'Сдвинуть влево', panRight: 'Сдвинуть вправо', panUp: 'Сдвинуть вверх', panDown: 'Сдвинуть вниз', resetView: 'Сбросить вид', reflowGraph: 'Перестроить граф', graphKeyboardHint: 'Колесо меняет масштаб, перетаскивание фона перемещает граф; перетащенный узел фиксируется, а перестроение снимает фиксацию; стрелки, плюс/минус и 0 также работают', legend: 'Легенда и фильтры связей', matched: 'Совпадение', selectedLabel: 'Выбрано', memoriesLabel: 'память', unknown: 'Неизвестно', nodeDetails: 'Детали узла', memoryDetails: 'Детали памяти', graphSummary: 'Сводка графа', weight: 'Вес', degree: 'Степень', relatedMemories: 'Связанная память', retrievalItems: 'Результаты поиска', topNodes: 'Ведущие узлы', topMemories: 'Ведущая память',
    memoryObjects: 'Объекты памяти', memoryConflicts: 'Конфликты', identityMappings: 'Сопоставление профилей', createMemoryObject: 'Создать объект', revisionHistory: 'История ревизий', sourceMessages: 'Исходные сообщения', relationsAndConflicts: 'Связи и конфликты', indexStatus: 'Статус индекса', unresolvedOwners: 'Неопределённые владельцы', sourceCoverage: 'Покрытие источниками', migrationStatus: 'Миграция объектов', retryIndex: 'Повторить индексацию', revisionConflictDraftKept: 'Конфликт версии; черновик сохранён', loadLatestVersion: 'Загрузить последнюю версию',
  },
};

export interface I18nContextValue { locale: Locale; t: (key: string) => string; }
export const I18nContext = createContext<I18nContextValue>({ locale: 'zh', t: (key) => dictionaries.zh[key] ?? key });
export function translate(locale: Locale, key: string) { return dictionaries[locale][key] ?? dictionaries.zh[key] ?? key; }
export function useI18n() { return useContext(I18nContext); }
